<?php
$buttonIds = explode(',', $instance['hosted_button_id']);
$currencies = explode(',', $instance['currencies']);
$symbols = explode(',', $instance['currency_symbols']);

$forms = bmab_generate_form_data($buttonIds, $currencies, $symbols);
$currency = bmab_get_currency_for_ip($instance['ip_info_token']);
?>
<div class="bmab-block">
    <?php if($description = $instance['description']): ?>
    <p class="bmab-comment">
        <?= $description; ?>
    </p>
    <?php endif; ?>
    <?php
    $form = $forms[$currency];
    ?>
    <form class="bmab-paypal-form" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick"/>
        <input type="hidden" name="hosted_button_id" value="<?= $form['buttonId']; ?>" />
        <input type="hidden" name="on0" value="Donation"/>
        <?php if ($amountTitle = $instance['amount_title']): ?>
        <h4 class="bmab-title">
            <label for="os0">
                <?= $amountTitle; ?>
            </label>
        </h4>
        <?php endif; ?>
        <?php if ($amountComment = $instance['amount_comment']): ?>
        <p class="bmab-comment">
            <?= $amountComment; ?>
        </p>
        <?php endif; ?>
        <select id="os0" name="os0">
            <option value="Pint">Pint <?= $form['symbol']; ?> 5,- <?= $currency; ?></option>
            <option selected="selected" value="Pitcher">Pitcher <?= $form['symbol']; ?> 10,- <?= $currency; ?></option>
            <option value="Case">Case <?= $form['symbol']; ?> 20,- <?= $currency; ?></option>
            <option value="Get wasted!">Get wasted! <?= $form['symbol']; ?> 50,- <?= $currency; ?></option>
        </select>
        <?php if ($pmTitle = $instance['pm_title']): ?>
        <input type="hidden" name="on1" value="Personal Message" />
        <h4 class="bmab-title">
            <label for="os1">
                <?= $pmTitle; ?>
            </label>
        </h4>
        <?php endif; ?>
        <?php if ($pmComment = $instance['pm_comment']): ?>
        <p class="bmab-comment">
            <?= $pmComment; ?>
        </p>
        <?php endif; ?>
        <?php if ($instance['pm_title']): ?>
        <textarea class="bmab-textarea" id="os1" type="text" name="os1" maxlength="200" rows="3"></textarea>
        <?php endif; ?>
        <input type="hidden" name="currency_code" value="<?= $currency; ?>" />
        <button class="bmab-button btn-lg" type="submit" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <span class="glyphicon glyphicon-heart"></span>
            <span class="bmab-button-text"><?= $instance['button_value']; ?></span>
        </button>
        <img alt="" border="0" src="https://www.paypalobjects.com/nl_NL/i/scr/pixel.gif" width="1" height="1" />
    </form>
    <?php if ($afterForm = $instance['after_form']): ?>
    <p class="bmab-comment">
        <?= $afterForm; ?>
    </p>
    <?php endif; ?>
</div>
